### ISSUE TITLE
ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

### ISSUE THREAD

**Issue by jabin753** [AlgusDark/awesome-reviews#1]
I tried to log in using wick@reviews.com and its pass, but nothing happens. Just throw "Your credentials are wrong".
I put a console.log seeking for user query object at pages/admin/login.ts before response:
```bash
{
  error: Error: Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
      at connect (C:\Users\Home\awesome-reviews\node_modules\serverless-mysql\index.js:80:15)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
}
```
My MySql DB:
```sql
-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         8.0.21 - MySQL Community Server - GPL
-- SO del servidor:              Win64
-- HeidiSQL Versión:             11.0.0.5919
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Volcando estructura de base de datos para awesomerevs
CREATE DATABASE IF NOT EXISTS `awesomerevs` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `awesomerevs`;

-- Volcando estructura para tabla awesomerevs.feedbacks
CREATE TABLE IF NOT EXISTS `feedbacks` (
  `reviewId` bigint NOT NULL,
  `questionId` bigint NOT NULL,
  `answer` text NOT NULL,
  PRIMARY KEY (`reviewId`,`questionId`),
  KEY `idx_rp_reviewId` (`reviewId`),
  KEY `idx_rp_questionId` (`questionId`),
  CONSTRAINT `feedbacks_ibfk_1` FOREIGN KEY (`questionId`) REFERENCES `questions` (`id`),
  CONSTRAINT `feedbacks_ibfk_2` FOREIGN KEY (`reviewId`) REFERENCES `reviews` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Volcando datos para la tabla awesomerevs.feedbacks: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `feedbacks` DISABLE KEYS */;
/*!40000 ALTER TABLE `feedbacks` ENABLE KEYS */;

-- Volcando estructura para tabla awesomerevs.questions
CREATE TABLE IF NOT EXISTS `questions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_slug` (`title`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Volcando datos para la tabla awesomerevs.questions: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `questions` DISABLE KEYS */;
INSERT INTO `questions` (`id`, `title`, `active`) VALUES
	(1, 'Does this employee exhibit leadership qualities in the roles they play in the company?', 1),
	(2, 'When this employee works with co-workers, what interpersonal skills do they demonstrate?', 1),
	(3, 'Does the employee effectively solve problems?', 1),
	(4, 'Does the employee appear to be motivated by their work-related tasks, job, and relationships?', 1);
/*!40000 ALTER TABLE `questions` ENABLE KEYS */;

-- Volcando estructura para tabla awesomerevs.reviews
CREATE TABLE IF NOT EXISTS `reviews` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `reviewerId` bigint NOT NULL,
  `revieweeId` bigint NOT NULL,
  `active` tinyint NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `idx_rp_reviewer` (`reviewerId`),
  KEY `idx_rp_reviewee` (`revieweeId`),
  CONSTRAINT `reviews_ibfk_1` FOREIGN KEY (`revieweeId`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `reviews_ibfk_2` FOREIGN KEY (`reviewerId`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Volcando datos para la tabla awesomerevs.reviews: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `reviews` DISABLE KEYS */;
/*!40000 ALTER TABLE `reviews` ENABLE KEYS */;

-- Volcando estructura para tabla awesomerevs.roles
CREATE TABLE IF NOT EXISTS `roles` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `title` varchar(75) NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_title` (`title`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Volcando datos para la tabla awesomerevs.roles: ~2 rows (aproximadamente)
/*!40000 ALTER TABLE `roles` DISABLE KEYS */;
INSERT INTO `roles` (`id`, `title`, `active`) VALUES
	(1, 'admin', 1),
	(2, 'employee', 1);
/*!40000 ALTER TABLE `roles` ENABLE KEYS */;

-- Volcando estructura para tabla awesomerevs.users
CREATE TABLE IF NOT EXISTS `users` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `roleId` bigint NOT NULL,
  `firstName` varchar(50) DEFAULT NULL,
  `lastName` varchar(50) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `password` varchar(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_email` (`email`),
  KEY `idx_user_role` (`roleId`),
  CONSTRAINT `fk_user_role` FOREIGN KEY (`roleId`) REFERENCES `roles` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Volcando datos para la tabla awesomerevs.users: ~7 rows (aproximadamente)
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`id`, `roleId`, `firstName`, `lastName`, `email`, `password`) VALUES
	(1, 1, 'John', 'Wick', 'wick@reviews.com', '1234'),
	(2, 2, 'John', 'Constantine', 'constantine@reviews.com', '1234'),
	(3, 2, 'Ted', 'Theodore Logan', 'ted@reviews.com', '1234'),
	(4, 2, 'Johnny', 'Mnemonic', 'mnemonic@reviews.com', '1234'),
	(5, 2, 'Johnny', 'Utah', 'utah@reviews.com', '1234'),
	(6, 2, 'Thomas', 'Anderson', 'neo@reviews.com', '1234'),
	(7, 2, 'Jack', 'Traven', 'jack@reviews.com', '1234'),
	(8, 1, 'Joseph Boss', 'Cuevas', 'jabin753@gmail.com', '1234');
/*!40000 ALTER TABLE `users` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
```

**Comment by AlgusDark** [comment]
Hi @jabin753 , thanks for reporting this and adding information.

The MySQL version you have is 8 and that version has a new auth method.

The simple solution is using a query for that:
```
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password'

Where root as your user localhost as your URL and password as your password

Then run this query to refresh privileges:

flush privileges;
```

[You can check more in stackoverflow](https://stackoverflow.com/questions/50093144/mysql-8-0-client-does-not-support-authentication-protocol-requested-by-server/56509065#56509065).

I will try with a different npm package to see if we can use the default auth for MySQL 8 as it brings better benefits.

Thanks for bringing this.

If this solves your problem, please add a comment with your solution and close the issue :)

**Comment by jabin753** [comment]
It worked. Thanks 🎉
